# Generated by Django 2.1.1 on 2018-11-10 00:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_user',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
