# Generated by Django 2.1.1 on 2018-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pro_img',
            field=models.ImageField(blank=True, default='', upload_to='pro_img'),
        ),
    ]
