# Generated by Django 2.1.1 on 2018-10-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(blank=True, default='', upload_to='pro_img')),
                ('pro', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_app.Project')),
            ],
        ),
    ]
