# Generated by Django 2.1.1 on 2018-11-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_group',
            field=models.BooleanField(),
        ),
    ]
