# Generated by Django 2.1.1 on 2018-11-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_rol',
            name='rol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rolInfo', to='project_app.rolInfo'),
        ),
        migrations.RemoveField(
            model_name='rolinfo',
            name='rol_location',
        ),
        migrations.AddField(
            model_name='rolinfo',
            name='rol_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='project_app.location'),
        ),
    ]
