# Generated by Django 2.1.1 on 2018-10-30 16:11

from django.db import migrations, models
import project_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='pro_img',
            field=models.ImageField(upload_to='pro_img', validators=[project_app.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
