# Generated by Django 2.1.1 on 2018-11-11 01:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('status', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_description',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_project',
            name='up_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='us_project', to='project_app.project'),
        ),
        migrations.AddField(
            model_name='user_project',
            name='up_rolInfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='us_rolInfo', to='project_app.rolInfo'),
        ),
        migrations.AddField(
            model_name='user_project',
            name='up_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='us_status', to='project_app.status'),
        ),
        migrations.AddField(
            model_name='user_project',
            name='up_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
