# Generated by Django 2.1.1 on 2018-11-03 01:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181027_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_description',
            field=ckeditor.fields.RichTextField(max_length=800, verbose_name='Descripción'),
        ),
    ]
