# Generated by Django 2.1.1 on 2018-11-10 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181110_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
