# Generated by Django 2.1.1 on 2018-11-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181111_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_project',
            name='up_status_text',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_project',
            name='up_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='up_project', to='project_app.project'),
        ),
        migrations.AlterField(
            model_name='user_project',
            name='up_rolInfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='up_rolInfo', to='project_app.rolInfo'),
        ),
        migrations.AlterField(
            model_name='user_project',
            name='up_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='upstatus', to='project_app.status'),
        ),
    ]
