# Generated by Django 2.1.1 on 2018-10-30 17:06

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181030_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_about_us',
            field=models.TextField(default='', max_length=800, verbose_name='Acerca de nosotros'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_phrase',
            field=models.CharField(default='', max_length=200, verbose_name='Indica si el proyecto tiene fines de lucro'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Video'),
        ),
    ]
