# Generated by Django 2.1.1 on 2018-10-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181025_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimg',
            name='pro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
