# Generated by Django 2.1.1 on 2018-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20181030_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_name',
            field=models.CharField(default='', max_length=40, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nombre del puesto'),
        ),
    ]
