# Generated by Django 2.1.1 on 2018-10-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20181025_1225'),
        ('project_app', '0005_auto_20181025_2259'),
    ]

    operations = [
    ]
