# Generated by Django 2.1.1 on 2018-10-30 18:59

from django.db import migrations, models
import project_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20181030_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de puestos disponibles'),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_description',
            field=models.TextField(default='', max_length=800, verbose_name='Descripción del rol'),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_due_date',
            field=models.DateField(validators=[project_app.validators.validate_past_date], verbose_name='Fecha límite para aplicar'),
        ),
    ]
