# Generated by Django 2.1.1 on 2018-11-16 03:15

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_auto_20181116_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
