# Generated by Django 2.1.1 on 2018-10-30 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_auto_20181030_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimg',
            name='pro_img',
            field=models.ImageField(upload_to='pro_img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
