# Generated by Django 2.1.1 on 2018-11-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20181114_2310'),
        ('project_app', '0006_auto_20181116_0315'),
    ]

    operations = [
    ]
