# Generated by Django 2.1.1 on 2018-10-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_auto_20181030_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_name',
            field=models.CharField(max_length=150, verbose_name='Nombre del puesto'),
        ),
    ]
