# Generated by Django 2.1.1 on 2018-10-30 21:07

from django.db import migrations, models
import project_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_auto_20181030_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_creation_date',
            field=models.DateField(validators=[project_app.validators.validate_future_date]),
        ),
    ]
