# Generated by Django 2.1.1 on 2018-10-15 16:25

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
