# Generated by Django 2.1.1 on 2018-10-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20181015_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
