# Generated by Django 2.1.1 on 2018-10-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
