# Generated by Django 2.1.1 on 2018-10-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20181020_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolinfo',
            name='rol_due_date',
            field=models.DateField(),
        ),
    ]
