# Generated by Django 2.1.1 on 2018-10-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_auto_20181020_2342'),
        ('app_one', '0004_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
    ]
