# Generated by Django 2.1.1 on 2018-10-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='Sin area', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Sin ubicacion', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(default='', max_length=40)),
                ('ProDescription', models.CharField(default='', max_length=40)),
                ('ProVideo', models.URLField()),
                ('ProAboutUs', models.CharField(default='', max_length=40)),
                ('ProFrase', models.CharField(default='', max_length=40)),
                ('ProCreationDate', models.DateField()),
                ('ProArea', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='appOne.area')),
                ('proLocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='appOne.location')),
            ],
        ),
    ]
