# Generated by Django 2.1.1 on 2018-10-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('area', models.CharField(default='Sin area', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location', models.CharField(default='Sin ubicacion', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(default='', max_length=40)),
                ('ProDescription', models.TextField(default='', max_length=800)),
                ('ProVideo', models.URLField()),
                ('ProAboutUs', models.TextField(default='', max_length=800)),
                ('ProFrase', models.CharField(default='', max_length=200)),
                ('ProCreationDate', models.DateField()),
                ('ProArea', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='appOne.area')),
                ('proLocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='appOne.location')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('rol', models.CharField(default='', max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='rolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLimite', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('rolDescripcion', models.TextField(default='', max_length=800)),
                ('RolLocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='appOne.location')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOne.rol')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proRoles',
            field=models.ManyToManyField(to='appOne.rolInfo'),
        ),
    ]
