# Generated by Django 2.1.1 on 2018-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
