# Generated by Django 2.1.1 on 2018-10-02 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Sin ubicacion', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre_proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProAboutUs',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProArea',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='appOne.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProCreationDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProFrase',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProName',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProVideo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(default='Sin area', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proLocation',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='appOne.location'),
            preserve_default=False,
        ),
    ]
