# Generated by Django 2.1.1 on 2018-10-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_rolinfo_rolarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolinfo',
            name='RolArea',
        ),
    ]
