# Generated by Django 2.1.1 on 2018-10-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20181012_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoimagen',
            name='proImage',
            field=models.ImageField(default='', upload_to='proImage'),
        ),
    ]
