# Generated by Django 2.1.1 on 2018-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0003_remove_rolinfo_rolarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
