# Generated by Django 2.1.1 on 2018-10-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0004_auto_20181004_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ProAboutUs',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ProDescription',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ProFrase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolinfo',
            name='rolDescripcion',
            field=models.TextField(default='', max_length=800),
        ),
    ]
