# Generated by Django 2.1.1 on 2018-10-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=50)),
                ('pro_description', models.TextField(default='', max_length=800)),
                ('pro_video', embed_video.fields.EmbedVideoField()),
                ('pro_about_us', models.TextField(default='', max_length=800)),
                ('pro_phrase', models.TextField(default='', max_length=700)),
                ('pro_creation_date', models.DateField()),
                ('pro_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='account_app.category')),
                ('pro_location', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='account_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='projectImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.ImageField(blank=True, default='', upload_to='pro_img')),
                ('pro', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('rol', models.CharField(default='', max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='rolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_due_date', models.DateField()),
                ('rol_amount', models.PositiveIntegerField(default=1)),
                ('rol_description', models.TextField(default='', max_length=800)),
                ('rol_location', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='account_app.location')),
                ('rol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='pro_roles',
            field=models.ManyToManyField(to='account_app.rolInfo'),
        ),
    ]
