# Generated by Django 2.1.1 on 2018-11-10 01:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20181109_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(default='My Bio', verbose_name='biografía'),
        ),
    ]
