# Generated by Django 2.1.1 on 2018-10-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_userprofileinfo_portfolio_site'),
        ('account_app', '0002_auto_20181025_1625'),
    ]

    operations = [
    ]
