# Generated by Django 2.1.1 on 2018-10-21 23:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pro_name'], 'verbose_name': 'projects', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
